// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYfs1aBZP9zel8IKvI8dEFMn1ueFTxBY',
    appId: '1:132778680853:web:9100caf2e79a2f5ec5e41c',
    messagingSenderId: '132778680853',
    projectId: 'tripzy-77',
    authDomain: 'tripzy-77.firebaseapp.com',
    storageBucket: 'tripzy-77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByZeTV3l1vDlV2XN47luVocW2VtmaSb4o',
    appId: '1:132778680853:android:62fec2966ab28f53c5e41c',
    messagingSenderId: '132778680853',
    projectId: 'tripzy-77',
    storageBucket: 'tripzy-77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3v6dMmCeSl6ehEpt8fqsbnBECXK5eR7Y',
    appId: '1:132778680853:ios:7cde8085f2a18e86c5e41c',
    messagingSenderId: '132778680853',
    projectId: 'tripzy-77',
    storageBucket: 'tripzy-77.firebasestorage.app',
    iosBundleId: 'com.example.travelPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3v6dMmCeSl6ehEpt8fqsbnBECXK5eR7Y',
    appId: '1:132778680853:ios:7cde8085f2a18e86c5e41c',
    messagingSenderId: '132778680853',
    projectId: 'tripzy-77',
    storageBucket: 'tripzy-77.firebasestorage.app',
    iosBundleId: 'com.example.travelPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYfs1aBZP9zel8IKvI8dEFMn1ueFTxBY',
    appId: '1:132778680853:web:1517390ebbfd114fc5e41c',
    messagingSenderId: '132778680853',
    projectId: 'tripzy-77',
    authDomain: 'tripzy-77.firebaseapp.com',
    storageBucket: 'tripzy-77.firebasestorage.app',
  );
}
